new_file=open("pepole1 exercise.text","w")
new_file.write("pepole name and place name" 
"rishabh - meerut \n"
"imtiyaz - delhi \n"
"nilima - cochin \n"
"rati - shimla \n"
"ayishah - delhi \n"
"raghu - shimla \n"
"naseer - kanpur \n"  
"karthikeyan - delhi \n"
"salma - jaipur \n"
"pankaj - delhi \n" 
"brijesh - delhi \n"
"govind - delhi\n"
"puneet - shimla\n"
"siddhi - delhi\n"
"suman - jaipur\n"
"rajeev - shimla\n"
"mohinder - delhi\n"
"rajendra - jaipur\n"
"priyanka - shimla\n"
"neela - delhi\n"
"sashi - jaipur\n"
"sarika - delhi\n"
"deepti - shimla\n"
"harshad - delhi\n"
"trishna - raipur\n"
"pradeep - jaipur\n"
"sekhar - delhi\n"
"nand - delhi\n"
"anoop - delhi\n"
"balwinder - tokyo")
new_file.close()
